site_name: Fact Checker

site_author: Mark Riise

copyright: 'Widgits Inc.'

nav:
- Home: 'index.md'
- Procedural: 
  - Call Center: 'callCenter.md'
  - API: 'api.md'
- Techinical: 
  - User Guide: 'userGuide.md'
  - FAW: 'faq.md'
- Copyright: 'copyright.md'
- Privacy: 'privacy.md'

plugins:
    - search

markdown_extensions:
    - fenced_code
    - admonition


theme: readthedocs